# ESB Lambda Base Image
# Base image containing the shared runtime.

FROM public.ecr.aws/lambda/python:3.12

# sitecustomize.py is auto-loaded at Python startup.
COPY site-packages/ /var/lang/lib/python3.12/site-packages/

# trace_bridge included in PYTHONPATH as a Lambda Layer.
COPY python/ /opt/python/
