# syntax=docker/dockerfile:1.7
# FunctionName: lambda-hello
FROM esb-lambda-base:latest

# ESB Runtime
COPY runtime-hooks/python/sitecustomize/site-packages/sitecustomize.py /opt/python/sitecustomize.py
ENV PYTHONPATH=/opt/python${PYTHONPATH:+:${PYTHONPATH}}

# Function code
COPY functions/hello/ ${LAMBDA_TASK_ROOT}/

# Handler
CMD [ "lambda_function.lambda_handler" ]
