// Code generated by schema-generate. DO NOT EDIT.

package schema

// AccessAssociation
type AccessAssociation struct {
	VpcEndpointId interface{} `json:"VpcEndpointId"`
}

// AlexaSkillEvent
type AlexaSkillEvent struct {
	Properties interface{} `json:"Properties,omitempty"`
	Type       string      `json:"Type"`
}

// AlexaSkillEventProperties
type AlexaSkillEventProperties struct {
	SkillId string `json:"SkillId,omitempty"`
}

// ApiAuth
type ApiAuth struct {
	ApiKeyRequired      bool        `json:"ApiKeyRequired,omitempty"`
	AuthorizationScopes []string    `json:"AuthorizationScopes,omitempty"`
	Authorizer          string      `json:"Authorizer,omitempty"`
	InvokeRole          interface{} `json:"InvokeRole,omitempty"`
	OverrideApiAuth     bool        `json:"OverrideApiAuth,omitempty"`
	ResourcePolicy      interface{} `json:"ResourcePolicy,omitempty"`
}

// ApiKey
type ApiKey struct {
	ApiKeyId    interface{} `json:"ApiKeyId,omitempty"`
	Description interface{} `json:"Description,omitempty"`
	ExpiresOn   interface{} `json:"ExpiresOn,omitempty"`
}

// AssumeRolePolicyDocument
type AssumeRolePolicyDocument struct{}

// Auth
type Auth struct {
	Additional       []Authorizer            `json:"Additional,omitempty"`
	LambdaAuthorizer *LambdaAuthorizerConfig `json:"LambdaAuthorizer,omitempty"`
	OpenIDConnect    *OpenIDConnectConfig    `json:"OpenIDConnect,omitempty"`
	Type             string                  `json:"Type"`
	UserPool         *UserPoolConfig         `json:"UserPool,omitempty"`
}

// Authorizer
type Authorizer struct {
	LambdaAuthorizer *LambdaAuthorizerConfig `json:"LambdaAuthorizer,omitempty"`
	OpenIDConnect    *OpenIDConnectConfig    `json:"OpenIDConnect,omitempty"`
	Type             string                  `json:"Type"`
	UserPool         *UserPoolConfig         `json:"UserPool,omitempty"`
}

// Cache
type Cache struct {
	ApiCachingBehavior       interface{} `json:"ApiCachingBehavior"`
	AtRestEncryptionEnabled  interface{} `json:"AtRestEncryptionEnabled,omitempty"`
	TransitEncryptionEnabled interface{} `json:"TransitEncryptionEnabled,omitempty"`
	Ttl                      interface{} `json:"Ttl"`
	Type                     interface{} `json:"Type"`
}

// Caching
type Caching struct {
	CachingKeys []interface{} `json:"CachingKeys,omitempty"`
	Ttl         interface{}   `json:"Ttl"`
}

// CapacityProviderConfig
type CapacityProviderConfig struct {
	Arn                                   interface{} `json:"Arn"`
	ExecutionEnvironmentMemoryGiBPerVCpu  interface{} `json:"ExecutionEnvironmentMemoryGiBPerVCpu,omitempty"`
	PerExecutionEnvironmentMaxConcurrency interface{} `json:"PerExecutionEnvironmentMaxConcurrency,omitempty"`
}

// CloudWatchLogsEvent
type CloudWatchLogsEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// CloudWatchLogsEventProperties
type CloudWatchLogsEventProperties struct {
	FilterPattern interface{} `json:"FilterPattern"`
	LogGroupName  interface{} `json:"LogGroupName"`
}

// CodeUri
type CodeUri struct {
	Bucket  interface{} `json:"Bucket"`
	Key     interface{} `json:"Key"`
	Version interface{} `json:"Version,omitempty"`
}

// CognitoAuthorizer
type CognitoAuthorizer struct {
	AuthorizationScopes []string    `json:"AuthorizationScopes,omitempty"`
	Identity            interface{} `json:"Identity,omitempty"`
	UserPoolArn         interface{} `json:"UserPoolArn"`
}

// CognitoAuthorizerIdentity
type CognitoAuthorizerIdentity struct {
	Header               string      `json:"Header,omitempty"`
	ReauthorizeEvery     interface{} `json:"ReauthorizeEvery,omitempty"`
	ValidationExpression string      `json:"ValidationExpression,omitempty"`
}

// CognitoEvent
type CognitoEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// CognitoEventProperties
type CognitoEventProperties struct {
	Trigger  interface{} `json:"Trigger"`
	UserPool interface{} `json:"UserPool"`
}

// ContentUri
type ContentUri struct {
	Bucket  interface{} `json:"Bucket"`
	Key     interface{} `json:"Key"`
	Version interface{} `json:"Version,omitempty"`
}

// Cors
type Cors struct {
	AllowCredentials bool   `json:"AllowCredentials,omitempty"`
	AllowHeaders     string `json:"AllowHeaders,omitempty"`
	AllowMethods     string `json:"AllowMethods,omitempty"`
	AllowOrigin      string `json:"AllowOrigin"`
	MaxAge           string `json:"MaxAge,omitempty"`
}

// DataSources
type DataSources struct {
	DynamoDb map[string]*DynamoDBDataSource `json:"DynamoDb,omitempty"`
	Lambda   map[string]*LambdaDataSource   `json:"Lambda,omitempty"`
}

// DeadLetterQueue
type DeadLetterQueue struct {
	TargetArn string `json:"TargetArn"`
	Type      string `json:"Type"`
}

// Definition
type Definition struct{}

// DefinitionBody
type DefinitionBody struct{}

// DefinitionSubstitutions
type DefinitionSubstitutions struct{}

// DeltaSync
type DeltaSync struct {
	BaseTableTTL       interface{} `json:"BaseTableTTL"`
	DeltaSyncTableName interface{} `json:"DeltaSyncTableName"`
	DeltaSyncTableTTL  interface{} `json:"DeltaSyncTableTTL"`
}

// DeploymentPreference
type DeploymentPreference struct {
	Alarms                interface{} `json:"Alarms,omitempty"`
	Enabled               interface{} `json:"Enabled,omitempty"`
	Hooks                 interface{} `json:"Hooks,omitempty"`
	PassthroughCondition  interface{} `json:"PassthroughCondition,omitempty"`
	Role                  interface{} `json:"Role,omitempty"`
	TriggerConfigurations interface{} `json:"TriggerConfigurations,omitempty"`
	Type                  interface{} `json:"Type,omitempty"`
}

// DocumentDBEvent
type DocumentDBEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// DocumentDBEventProperties
type DocumentDBEventProperties struct {
	BatchSize                      interface{} `json:"BatchSize,omitempty"`
	Cluster                        interface{} `json:"Cluster"`
	CollectionName                 interface{} `json:"CollectionName,omitempty"`
	DatabaseName                   interface{} `json:"DatabaseName"`
	Enabled                        interface{} `json:"Enabled,omitempty"`
	FilterCriteria                 interface{} `json:"FilterCriteria,omitempty"`
	FullDocument                   interface{} `json:"FullDocument,omitempty"`
	MaximumBatchingWindowInSeconds interface{} `json:"MaximumBatchingWindowInSeconds,omitempty"`
	SecretsManagerKmsKeyId         string      `json:"SecretsManagerKmsKeyId,omitempty"`
	SourceAccessConfigurations     interface{} `json:"SourceAccessConfigurations"`
	StartingPosition               interface{} `json:"StartingPosition,omitempty"`
	StartingPositionTimestamp      interface{} `json:"StartingPositionTimestamp,omitempty"`
}

// DomainName
type DomainName struct {
	CertificateArn interface{} `json:"CertificateArn"`
	Description    interface{} `json:"Description,omitempty"`
	DomainName     interface{} `json:"DomainName"`
}

// DynamoDBDataSource
type DynamoDBDataSource struct {
	DeltaSync            *DeltaSync  `json:"DeltaSync,omitempty"`
	Description          interface{} `json:"Description,omitempty"`
	Name                 interface{} `json:"Name,omitempty"`
	Permissions          []string    `json:"Permissions,omitempty"`
	Region               interface{} `json:"Region,omitempty"`
	ServiceRoleArn       interface{} `json:"ServiceRoleArn,omitempty"`
	TableArn             interface{} `json:"TableArn,omitempty"`
	TableName            interface{} `json:"TableName"`
	UseCallerCredentials interface{} `json:"UseCallerCredentials,omitempty"`
	Versioned            interface{} `json:"Versioned,omitempty"`
}

// DynamoDBEvent
type DynamoDBEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// DynamoDBEventProperties
type DynamoDBEventProperties struct {
	BatchSize                      interface{} `json:"BatchSize,omitempty"`
	BisectBatchOnFunctionError     interface{} `json:"BisectBatchOnFunctionError,omitempty"`
	DestinationConfig              interface{} `json:"DestinationConfig,omitempty"`
	Enabled                        interface{} `json:"Enabled,omitempty"`
	FilterCriteria                 interface{} `json:"FilterCriteria,omitempty"`
	FunctionResponseTypes          interface{} `json:"FunctionResponseTypes,omitempty"`
	KmsKeyArn                      interface{} `json:"KmsKeyArn,omitempty"`
	MaximumBatchingWindowInSeconds interface{} `json:"MaximumBatchingWindowInSeconds,omitempty"`
	MaximumRecordAgeInSeconds      interface{} `json:"MaximumRecordAgeInSeconds,omitempty"`
	MaximumRetryAttempts           interface{} `json:"MaximumRetryAttempts,omitempty"`
	MetricsConfig                  interface{} `json:"MetricsConfig,omitempty"`
	ParallelizationFactor          interface{} `json:"ParallelizationFactor,omitempty"`
	StartingPosition               interface{} `json:"StartingPosition,omitempty"`
	StartingPositionTimestamp      interface{} `json:"StartingPositionTimestamp,omitempty"`
	Stream                         interface{} `json:"Stream"`
	TumblingWindowInSeconds        interface{} `json:"TumblingWindowInSeconds,omitempty"`
}

// EmbeddedConnector
type EmbeddedConnector struct {
	Condition           interface{}                  `json:"Condition,omitempty"`
	DeletionPolicy      interface{}                  `json:"DeletionPolicy,omitempty"`
	DependsOn           interface{}                  `json:"DependsOn,omitempty"`
	IgnoreGlobals       interface{}                  `json:"IgnoreGlobals,omitempty"`
	Metadata            interface{}                  `json:"Metadata,omitempty"`
	Properties          *EmbeddedConnectorProperties `json:"Properties"`
	UpdateReplacePolicy interface{}                  `json:"UpdateReplacePolicy,omitempty"`
}

// EmbeddedConnectorProperties
type EmbeddedConnectorProperties struct {
	Destination     interface{} `json:"Destination"`
	Permissions     []string    `json:"Permissions"`
	SourceReference interface{} `json:"SourceReference,omitempty"`
}

// EndpointConfiguration
type EndpointConfiguration struct {
	IpAddressType  interface{} `json:"IpAddressType,omitempty"`
	Type           interface{} `json:"Type,omitempty"`
	VPCEndpointIds interface{} `json:"VPCEndpointIds,omitempty"`
}

// EventInvokeConfig
type EventInvokeConfig struct {
	DestinationConfig        interface{} `json:"DestinationConfig,omitempty"`
	MaximumEventAgeInSeconds int64       `json:"MaximumEventAgeInSeconds,omitempty"`
	MaximumRetryAttempts     int64       `json:"MaximumRetryAttempts,omitempty"`
}

// EventInvokeDestinationConfig
type EventInvokeDestinationConfig struct {
	OnFailure interface{} `json:"OnFailure,omitempty"`
	OnSuccess interface{} `json:"OnSuccess,omitempty"`
}

// EventInvokeOnFailure
type EventInvokeOnFailure struct {
	Destination interface{} `json:"Destination,omitempty"`
	Type        string      `json:"Type,omitempty"`
}

// EventInvokeOnSuccess
type EventInvokeOnSuccess struct {
	Destination interface{} `json:"Destination,omitempty"`
	Type        string      `json:"Type,omitempty"`
}

// EventsScheduleProperties
type EventsScheduleProperties struct {
	DeadLetterConfig interface{} `json:"DeadLetterConfig,omitempty"`
	Description      interface{} `json:"Description,omitempty"`
	Enabled          bool        `json:"Enabled,omitempty"`
	Input            interface{} `json:"Input,omitempty"`
	Name             interface{} `json:"Name,omitempty"`
	RetryPolicy      interface{} `json:"RetryPolicy,omitempty"`
	Schedule         interface{} `json:"Schedule,omitempty"`
	State            interface{} `json:"State,omitempty"`
}

// Function
type Function struct {
	CodeUri      interface{} `json:"CodeUri,omitempty"`
	DataSource   interface{} `json:"DataSource,omitempty"`
	Description  interface{} `json:"Description,omitempty"`
	Id           interface{} `json:"Id,omitempty"`
	InlineCode   interface{} `json:"InlineCode,omitempty"`
	MaxBatchSize interface{} `json:"MaxBatchSize,omitempty"`
	Name         string      `json:"Name,omitempty"`
	Runtime      *Runtime    `json:"Runtime,omitempty"`
	Sync         *Sync       `json:"Sync,omitempty"`
}

// FunctionUrlConfig
type FunctionUrlConfig struct {
	AuthType   interface{} `json:"AuthType"`
	Cors       interface{} `json:"Cors,omitempty"`
	InvokeMode interface{} `json:"InvokeMode,omitempty"`
}

// GatewayResponses
type GatewayResponses struct{}

// Globals
type Globals struct {
	AccessLogSettings    interface{} `json:"AccessLogSettings,omitempty"`
	Auth                 interface{} `json:"Auth,omitempty"`
	CorsConfiguration    interface{} `json:"CorsConfiguration,omitempty"`
	DefaultRouteSettings interface{} `json:"DefaultRouteSettings,omitempty"`
	Domain               interface{} `json:"Domain,omitempty"`
	FailOnWarnings       interface{} `json:"FailOnWarnings,omitempty"`
	PropagateTags        bool        `json:"PropagateTags,omitempty"`
	RouteSettings        interface{} `json:"RouteSettings,omitempty"`
	StageVariables       interface{} `json:"StageVariables,omitempty"`
	Tags                 *Tags       `json:"Tags,omitempty"`
}

// Hooks
type Hooks struct {
	PostTraffic interface{} `json:"PostTraffic,omitempty"`
	PreTraffic  interface{} `json:"PreTraffic,omitempty"`
}

// HttpApiAuth
type HttpApiAuth struct {
	AuthorizationScopes []string `json:"AuthorizationScopes,omitempty"`
	Authorizer          string   `json:"Authorizer,omitempty"`
}

// HttpApiEvent
type HttpApiEvent struct {
	Properties interface{} `json:"Properties,omitempty"`
	Type       string      `json:"Type"`
}

// HttpApiEventProperties
type HttpApiEventProperties struct {
	ApiId                interface{} `json:"ApiId,omitempty"`
	Auth                 interface{} `json:"Auth,omitempty"`
	Method               string      `json:"Method,omitempty"`
	Path                 string      `json:"Path,omitempty"`
	PayloadFormatVersion interface{} `json:"PayloadFormatVersion,omitempty"`
	RouteSettings        interface{} `json:"RouteSettings,omitempty"`
	TimeoutInMillis      interface{} `json:"TimeoutInMillis,omitempty"`
}

// InstanceRequirements
type InstanceRequirements struct {
	AllowedTypes  interface{} `json:"AllowedTypes,omitempty"`
	Architectures interface{} `json:"Architectures,omitempty"`
	ExcludedTypes interface{} `json:"ExcludedTypes,omitempty"`
}

// IoTRuleEvent
type IoTRuleEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// IoTRuleEventProperties
type IoTRuleEventProperties struct {
	AwsIotSqlVersion interface{} `json:"AwsIotSqlVersion,omitempty"`
	Sql              interface{} `json:"Sql"`
}

// KinesisEvent
type KinesisEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// KinesisEventProperties
type KinesisEventProperties struct {
	BatchSize                      interface{} `json:"BatchSize,omitempty"`
	BisectBatchOnFunctionError     interface{} `json:"BisectBatchOnFunctionError,omitempty"`
	DestinationConfig              interface{} `json:"DestinationConfig,omitempty"`
	Enabled                        interface{} `json:"Enabled,omitempty"`
	FilterCriteria                 interface{} `json:"FilterCriteria,omitempty"`
	FunctionResponseTypes          interface{} `json:"FunctionResponseTypes,omitempty"`
	KmsKeyArn                      interface{} `json:"KmsKeyArn,omitempty"`
	MaximumBatchingWindowInSeconds interface{} `json:"MaximumBatchingWindowInSeconds,omitempty"`
	MaximumRecordAgeInSeconds      interface{} `json:"MaximumRecordAgeInSeconds,omitempty"`
	MaximumRetryAttempts           interface{} `json:"MaximumRetryAttempts,omitempty"`
	MetricsConfig                  interface{} `json:"MetricsConfig,omitempty"`
	ParallelizationFactor          interface{} `json:"ParallelizationFactor,omitempty"`
	StartingPosition               interface{} `json:"StartingPosition,omitempty"`
	StartingPositionTimestamp      interface{} `json:"StartingPositionTimestamp,omitempty"`
	Stream                         interface{} `json:"Stream"`
	TumblingWindowInSeconds        interface{} `json:"TumblingWindowInSeconds,omitempty"`
}

// LambdaAuthorizer
type LambdaAuthorizer struct {
	AuthorizerPayloadFormatVersion   interface{} `json:"AuthorizerPayloadFormatVersion"`
	EnableFunctionDefaultPermissions bool        `json:"EnableFunctionDefaultPermissions,omitempty"`
	EnableSimpleResponses            bool        `json:"EnableSimpleResponses,omitempty"`
	FunctionArn                      interface{} `json:"FunctionArn"`
	FunctionInvokeRole               interface{} `json:"FunctionInvokeRole,omitempty"`
	Identity                         interface{} `json:"Identity,omitempty"`
}

// LambdaAuthorizerConfig
type LambdaAuthorizerConfig struct {
	AuthorizerResultTtlInSeconds interface{} `json:"AuthorizerResultTtlInSeconds,omitempty"`
	AuthorizerUri                interface{} `json:"AuthorizerUri"`
	IdentityValidationExpression interface{} `json:"IdentityValidationExpression,omitempty"`
}

// LambdaAuthorizerIdentity
type LambdaAuthorizerIdentity struct {
	Context          []string `json:"Context,omitempty"`
	Headers          []string `json:"Headers,omitempty"`
	QueryStrings     []string `json:"QueryStrings,omitempty"`
	ReauthorizeEvery int64    `json:"ReauthorizeEvery,omitempty"`
	StageVariables   []string `json:"StageVariables,omitempty"`
}

// LambdaConflictHandlerConfig
type LambdaConflictHandlerConfig struct {
	LambdaConflictHandlerArn interface{} `json:"LambdaConflictHandlerArn"`
}

// LambdaDataSource
type LambdaDataSource struct {
	Description    interface{} `json:"Description,omitempty"`
	FunctionArn    interface{} `json:"FunctionArn"`
	Name           interface{} `json:"Name,omitempty"`
	ServiceRoleArn interface{} `json:"ServiceRoleArn,omitempty"`
}

// LambdaRequestAuthorizer
type LambdaRequestAuthorizer struct {
	DisableFunctionDefaultPermissions bool        `json:"DisableFunctionDefaultPermissions,omitempty"`
	FunctionArn                       interface{} `json:"FunctionArn"`
	FunctionInvokeRole                string      `json:"FunctionInvokeRole,omitempty"`
	FunctionPayloadType               string      `json:"FunctionPayloadType,omitempty"`
	Identity                          interface{} `json:"Identity,omitempty"`
}

// LambdaRequestAuthorizerIdentity
type LambdaRequestAuthorizerIdentity struct {
	Context          []string    `json:"Context,omitempty"`
	Headers          []string    `json:"Headers,omitempty"`
	QueryStrings     []string    `json:"QueryStrings,omitempty"`
	ReauthorizeEvery interface{} `json:"ReauthorizeEvery,omitempty"`
	StageVariables   []string    `json:"StageVariables,omitempty"`
}

// LambdaTokenAuthorizer
type LambdaTokenAuthorizer struct {
	DisableFunctionDefaultPermissions bool        `json:"DisableFunctionDefaultPermissions,omitempty"`
	FunctionArn                       interface{} `json:"FunctionArn"`
	FunctionInvokeRole                string      `json:"FunctionInvokeRole,omitempty"`
	FunctionPayloadType               string      `json:"FunctionPayloadType,omitempty"`
	Identity                          interface{} `json:"Identity,omitempty"`
}

// LambdaTokenAuthorizerIdentity
type LambdaTokenAuthorizerIdentity struct {
	Header               string      `json:"Header,omitempty"`
	ReauthorizeEvery     interface{} `json:"ReauthorizeEvery,omitempty"`
	ValidationExpression string      `json:"ValidationExpression,omitempty"`
}

// Location
type Location struct {
	ApplicationId   interface{} `json:"ApplicationId"`
	SemanticVersion interface{} `json:"SemanticVersion"`
}

// Logging
type Logging struct {
	CloudWatchLogsRoleArn interface{} `json:"CloudWatchLogsRoleArn,omitempty"`
	ExcludeVerboseContent interface{} `json:"ExcludeVerboseContent,omitempty"`
	FieldLogLevel         interface{} `json:"FieldLogLevel,omitempty"`
}

// MQEvent
type MQEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// MQEventProperties
type MQEventProperties struct {
	BatchSize                      interface{} `json:"BatchSize,omitempty"`
	Broker                         interface{} `json:"Broker"`
	DynamicPolicyName              bool        `json:"DynamicPolicyName,omitempty"`
	Enabled                        interface{} `json:"Enabled,omitempty"`
	FilterCriteria                 interface{} `json:"FilterCriteria,omitempty"`
	KmsKeyArn                      interface{} `json:"KmsKeyArn,omitempty"`
	MaximumBatchingWindowInSeconds interface{} `json:"MaximumBatchingWindowInSeconds,omitempty"`
	Queues                         interface{} `json:"Queues"`
	SecretsManagerKmsKeyId         string      `json:"SecretsManagerKmsKeyId,omitempty"`
	SourceAccessConfigurations     interface{} `json:"SourceAccessConfigurations"`
}

// MSKEvent
type MSKEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// MSKEventProperties
type MSKEventProperties struct {
	BisectBatchOnFunctionError     interface{} `json:"BisectBatchOnFunctionError,omitempty"`
	ConsumerGroupId                interface{} `json:"ConsumerGroupId,omitempty"`
	DestinationConfig              interface{} `json:"DestinationConfig,omitempty"`
	Enabled                        interface{} `json:"Enabled,omitempty"`
	FilterCriteria                 interface{} `json:"FilterCriteria,omitempty"`
	FunctionResponseTypes          interface{} `json:"FunctionResponseTypes,omitempty"`
	KmsKeyArn                      interface{} `json:"KmsKeyArn,omitempty"`
	MaximumBatchingWindowInSeconds interface{} `json:"MaximumBatchingWindowInSeconds,omitempty"`
	MaximumRecordAgeInSeconds      interface{} `json:"MaximumRecordAgeInSeconds,omitempty"`
	MaximumRetryAttempts           interface{} `json:"MaximumRetryAttempts,omitempty"`
	ProvisionedPollerConfig        interface{} `json:"ProvisionedPollerConfig,omitempty"`
	SchemaRegistryConfig           interface{} `json:"SchemaRegistryConfig,omitempty"`
	SourceAccessConfigurations     interface{} `json:"SourceAccessConfigurations,omitempty"`
	StartingPosition               interface{} `json:"StartingPosition,omitempty"`
	StartingPositionTimestamp      interface{} `json:"StartingPositionTimestamp,omitempty"`
	Stream                         interface{} `json:"Stream"`
	Topics                         interface{} `json:"Topics"`
}

// MainGlobals
type MainGlobals struct {
	Api              *SamtranslatorInternalSchemaSourceAwsServerlessApiGlobals              `json:"Api,omitempty"`
	CapacityProvider *SamtranslatorInternalSchemaSourceAwsServerlessCapacityProviderGlobals `json:"CapacityProvider,omitempty"`
	Function         *SamtranslatorInternalSchemaSourceAwsServerlessFunctionGlobals         `json:"Function,omitempty"`
	HttpApi          *Globals                                                               `json:"HttpApi,omitempty"`
	LayerVersion     *SamtranslatorInternalSchemaSourceAwsServerlessLayerversionGlobals     `json:"LayerVersion,omitempty"`
	SimpleTable      *SamtranslatorInternalSchemaSourceAwsServerlessSimpletableGlobals      `json:"SimpleTable,omitempty"`
	StateMachine     *Globals                                                               `json:"StateMachine,omitempty"`
}

// Models
type Models struct{}

// OAuth2Authorizer
type OAuth2Authorizer struct {
	AuthorizationScopes []string    `json:"AuthorizationScopes,omitempty"`
	IdentitySource      string      `json:"IdentitySource,omitempty"`
	JwtConfiguration    interface{} `json:"JwtConfiguration,omitempty"`
}

// OpenIDConnectConfig
type OpenIDConnectConfig struct {
	AuthTTL  interface{} `json:"AuthTTL,omitempty"`
	ClientId interface{} `json:"ClientId,omitempty"`
	IatTTL   interface{} `json:"IatTTL,omitempty"`
	Issuer   interface{} `json:"Issuer,omitempty"`
}

// PrimaryKey
type PrimaryKey struct {
	Name interface{} `json:"Name"`
	Type interface{} `json:"Type"`
}

// Properties
type Properties struct {
	CapacityProviderName interface{} `json:"CapacityProviderName,omitempty"`
	InstanceRequirements interface{} `json:"InstanceRequirements,omitempty"`
	KmsKeyArn            interface{} `json:"KmsKeyArn,omitempty"`
	OperatorRole         interface{} `json:"OperatorRole,omitempty"`
	PropagateTags        bool        `json:"PropagateTags,omitempty"`
	ScalingConfig        interface{} `json:"ScalingConfig,omitempty"`
	Tags                 *Tags       `json:"Tags,omitempty"`
	VpcConfig            interface{} `json:"VpcConfig"`
}

// Ref
type Ref struct {
	Ref string `json:"Ref"`
}

// RequestModel
type RequestModel struct {
	Model              string `json:"Model"`
	Required           bool   `json:"Required,omitempty"`
	ValidateBody       bool   `json:"ValidateBody,omitempty"`
	ValidateParameters bool   `json:"ValidateParameters,omitempty"`
}

// RequestParameters
type RequestParameters struct {
	Caching  bool `json:"Caching,omitempty"`
	Required bool `json:"Required,omitempty"`
}

// Resolver
type Resolver struct {
	Caching      *Caching    `json:"Caching,omitempty"`
	CodeUri      interface{} `json:"CodeUri,omitempty"`
	FieldName    string      `json:"FieldName,omitempty"`
	InlineCode   interface{} `json:"InlineCode,omitempty"`
	MaxBatchSize interface{} `json:"MaxBatchSize,omitempty"`
	Pipeline     []string    `json:"Pipeline,omitempty"`
	Runtime      *Runtime    `json:"Runtime,omitempty"`
	Sync         *Sync       `json:"Sync,omitempty"`
}

// ResourceReference
type ResourceReference struct {
	Arn        interface{} `json:"Arn,omitempty"`
	Id         string      `json:"Id,omitempty"`
	Name       interface{} `json:"Name,omitempty"`
	Qualifier  interface{} `json:"Qualifier,omitempty"`
	QueueUrl   interface{} `json:"QueueUrl,omitempty"`
	ResourceId interface{} `json:"ResourceId,omitempty"`
	RoleName   interface{} `json:"RoleName,omitempty"`
	Type       string      `json:"Type,omitempty"`
}

// Runtime
type Runtime struct {
	Name    interface{} `json:"Name"`
	Version interface{} `json:"Version"`
}

// S3Event
type S3Event struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// S3EventProperties
type S3EventProperties struct {
	Bucket interface{} `json:"Bucket"`
	Events interface{} `json:"Events"`
	Filter interface{} `json:"Filter,omitempty"`
}

// SNSEvent
type SNSEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// SNSEventProperties
type SNSEventProperties struct {
	FilterPolicy      interface{} `json:"FilterPolicy,omitempty"`
	FilterPolicyScope interface{} `json:"FilterPolicyScope,omitempty"`
	Region            interface{} `json:"Region,omitempty"`
	SqsSubscription   interface{} `json:"SqsSubscription,omitempty"`
	Topic             interface{} `json:"Topic"`
}

// SQSEvent
type SQSEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// SQSEventProperties
type SQSEventProperties struct {
	BatchSize                      interface{} `json:"BatchSize,omitempty"`
	Enabled                        interface{} `json:"Enabled,omitempty"`
	FilterCriteria                 interface{} `json:"FilterCriteria,omitempty"`
	FunctionResponseTypes          interface{} `json:"FunctionResponseTypes,omitempty"`
	KmsKeyArn                      interface{} `json:"KmsKeyArn,omitempty"`
	MaximumBatchingWindowInSeconds interface{} `json:"MaximumBatchingWindowInSeconds,omitempty"`
	MetricsConfig                  interface{} `json:"MetricsConfig,omitempty"`
	Queue                          interface{} `json:"Queue"`
	ScalingConfig                  interface{} `json:"ScalingConfig,omitempty"`
}

// SamModel
type SamModel struct {
	Globals   *MainGlobals           `json:"Globals,omitempty"`
	Resources map[string]interface{} `json:"Resources"`
}

// SamtranslatorInternalSchemaSourceAnyCfnResourceResource
type SamtranslatorInternalSchemaSourceAnyCfnResourceResource struct {
	Type string `json:"Type"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessApiAuth
type SamtranslatorInternalSchemaSourceAwsServerlessApiAuth struct {
	AddApiKeyRequiredToCorsPreflight    bool                   `json:"AddApiKeyRequiredToCorsPreflight,omitempty"`
	AddDefaultAuthorizerToCorsPreflight bool                   `json:"AddDefaultAuthorizerToCorsPreflight,omitempty"`
	ApiKeyRequired                      bool                   `json:"ApiKeyRequired,omitempty"`
	Authorizers                         map[string]interface{} `json:"Authorizers,omitempty"`
	DefaultAuthorizer                   string                 `json:"DefaultAuthorizer,omitempty"`
	InvokeRole                          string                 `json:"InvokeRole,omitempty"`
	ResourcePolicy                      interface{}            `json:"ResourcePolicy,omitempty"`
	UsagePlan                           interface{}            `json:"UsagePlan,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessApiDefinitionUri
type SamtranslatorInternalSchemaSourceAwsServerlessApiDefinitionUri struct {
	Bucket  interface{} `json:"Bucket"`
	Key     interface{} `json:"Key"`
	Version interface{} `json:"Version,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessApiDomain
type SamtranslatorInternalSchemaSourceAwsServerlessApiDomain struct {
	AccessAssociation                   *AccessAssociation `json:"AccessAssociation,omitempty"`
	BasePath                            interface{}        `json:"BasePath,omitempty"`
	CertificateArn                      interface{}        `json:"CertificateArn"`
	DomainName                          interface{}        `json:"DomainName"`
	EndpointConfiguration               interface{}        `json:"EndpointConfiguration,omitempty"`
	IpAddressType                       interface{}        `json:"IpAddressType,omitempty"`
	MutualTlsAuthentication             interface{}        `json:"MutualTlsAuthentication,omitempty"`
	NormalizeBasePath                   bool               `json:"NormalizeBasePath,omitempty"`
	OwnershipVerificationCertificateArn interface{}        `json:"OwnershipVerificationCertificateArn,omitempty"`
	Policy                              interface{}        `json:"Policy,omitempty"`
	Route53                             interface{}        `json:"Route53,omitempty"`
	SecurityPolicy                      interface{}        `json:"SecurityPolicy,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessApiGlobals
type SamtranslatorInternalSchemaSourceAwsServerlessApiGlobals struct {
	AccessLogSetting       interface{}       `json:"AccessLogSetting,omitempty"`
	AlwaysDeploy           bool              `json:"AlwaysDeploy,omitempty"`
	Auth                   interface{}       `json:"Auth,omitempty"`
	BinaryMediaTypes       interface{}       `json:"BinaryMediaTypes,omitempty"`
	CacheClusterEnabled    interface{}       `json:"CacheClusterEnabled,omitempty"`
	CacheClusterSize       interface{}       `json:"CacheClusterSize,omitempty"`
	CanarySetting          interface{}       `json:"CanarySetting,omitempty"`
	Cors                   interface{}       `json:"Cors,omitempty"`
	DefinitionUri          interface{}       `json:"DefinitionUri,omitempty"`
	Domain                 interface{}       `json:"Domain,omitempty"`
	EndpointConfiguration  interface{}       `json:"EndpointConfiguration,omitempty"`
	GatewayResponses       *GatewayResponses `json:"GatewayResponses,omitempty"`
	MergeDefinitions       bool              `json:"MergeDefinitions,omitempty"`
	MethodSettings         interface{}       `json:"MethodSettings,omitempty"`
	MinimumCompressionSize interface{}       `json:"MinimumCompressionSize,omitempty"`
	Name                   interface{}       `json:"Name,omitempty"`
	OpenApiVersion         interface{}       `json:"OpenApiVersion,omitempty"`
	PropagateTags          bool              `json:"PropagateTags,omitempty"`
	TracingEnabled         interface{}       `json:"TracingEnabled,omitempty"`
	Variables              interface{}       `json:"Variables,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessApiProperties
type SamtranslatorInternalSchemaSourceAwsServerlessApiProperties struct {
	AccessLogSetting          interface{}       `json:"AccessLogSetting,omitempty"`
	AlwaysDeploy              bool              `json:"AlwaysDeploy,omitempty"`
	ApiKeySourceType          interface{}       `json:"ApiKeySourceType,omitempty"`
	Auth                      interface{}       `json:"Auth,omitempty"`
	BinaryMediaTypes          interface{}       `json:"BinaryMediaTypes,omitempty"`
	CacheClusterEnabled       interface{}       `json:"CacheClusterEnabled,omitempty"`
	CacheClusterSize          interface{}       `json:"CacheClusterSize,omitempty"`
	CanarySetting             interface{}       `json:"CanarySetting,omitempty"`
	Cors                      interface{}       `json:"Cors,omitempty"`
	DefinitionBody            *DefinitionBody   `json:"DefinitionBody,omitempty"`
	DefinitionUri             interface{}       `json:"DefinitionUri,omitempty"`
	Description               interface{}       `json:"Description,omitempty"`
	DisableExecuteApiEndpoint interface{}       `json:"DisableExecuteApiEndpoint,omitempty"`
	Domain                    interface{}       `json:"Domain,omitempty"`
	EndpointConfiguration     interface{}       `json:"EndpointConfiguration,omitempty"`
	FailOnWarnings            interface{}       `json:"FailOnWarnings,omitempty"`
	GatewayResponses          *GatewayResponses `json:"GatewayResponses,omitempty"`
	MergeDefinitions          bool              `json:"MergeDefinitions,omitempty"`
	MethodSettings            interface{}       `json:"MethodSettings,omitempty"`
	MinimumCompressionSize    interface{}       `json:"MinimumCompressionSize,omitempty"`
	Mode                      interface{}       `json:"Mode,omitempty"`
	Models                    *Models           `json:"Models,omitempty"`
	Name                      interface{}       `json:"Name,omitempty"`
	OpenApiVersion            interface{}       `json:"OpenApiVersion,omitempty"`
	Policy                    interface{}       `json:"Policy,omitempty"`
	PropagateTags             bool              `json:"PropagateTags,omitempty"`
	StageName                 interface{}       `json:"StageName"`
	Tags                      *Tags             `json:"Tags,omitempty"`
	TracingEnabled            interface{}       `json:"TracingEnabled,omitempty"`
	Variables                 interface{}       `json:"Variables,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessApiResource
type SamtranslatorInternalSchemaSourceAwsServerlessApiResource struct {
	Condition           interface{}                                                  `json:"Condition,omitempty"`
	Connectors          map[string]*EmbeddedConnector                                `json:"Connectors,omitempty"`
	DeletionPolicy      interface{}                                                  `json:"DeletionPolicy,omitempty"`
	DependsOn           interface{}                                                  `json:"DependsOn,omitempty"`
	IgnoreGlobals       interface{}                                                  `json:"IgnoreGlobals,omitempty"`
	Metadata            interface{}                                                  `json:"Metadata,omitempty"`
	Properties          *SamtranslatorInternalSchemaSourceAwsServerlessApiProperties `json:"Properties"`
	Type                string                                                       `json:"Type"`
	UpdateReplacePolicy interface{}                                                  `json:"UpdateReplacePolicy,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessApiResourcePolicy
type SamtranslatorInternalSchemaSourceAwsServerlessApiResourcePolicy struct {
	AwsAccountBlacklist    []interface{} `json:"AwsAccountBlacklist,omitempty"`
	AwsAccountWhitelist    []interface{} `json:"AwsAccountWhitelist,omitempty"`
	CustomStatements       []interface{} `json:"CustomStatements,omitempty"`
	IntrinsicVpcBlacklist  []interface{} `json:"IntrinsicVpcBlacklist,omitempty"`
	IntrinsicVpcWhitelist  []interface{} `json:"IntrinsicVpcWhitelist,omitempty"`
	IntrinsicVpceBlacklist []interface{} `json:"IntrinsicVpceBlacklist,omitempty"`
	IntrinsicVpceWhitelist []interface{} `json:"IntrinsicVpceWhitelist,omitempty"`
	IpRangeBlacklist       []interface{} `json:"IpRangeBlacklist,omitempty"`
	IpRangeWhitelist       []interface{} `json:"IpRangeWhitelist,omitempty"`
	SourceVpcBlacklist     []interface{} `json:"SourceVpcBlacklist,omitempty"`
	SourceVpcWhitelist     []interface{} `json:"SourceVpcWhitelist,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessApiRoute53
type SamtranslatorInternalSchemaSourceAwsServerlessApiRoute53 struct {
	DistributionDomainName  interface{} `json:"DistributionDomainName,omitempty"`
	EvaluateTargetHealth    interface{} `json:"EvaluateTargetHealth,omitempty"`
	HostedZoneId            interface{} `json:"HostedZoneId,omitempty"`
	HostedZoneName          interface{} `json:"HostedZoneName,omitempty"`
	IpV6                    bool        `json:"IpV6,omitempty"`
	Region                  interface{} `json:"Region,omitempty"`
	SeparateRecordSetGroup  bool        `json:"SeparateRecordSetGroup,omitempty"`
	SetIdentifier           interface{} `json:"SetIdentifier,omitempty"`
	VpcEndpointDomainName   interface{} `json:"VpcEndpointDomainName,omitempty"`
	VpcEndpointHostedZoneId interface{} `json:"VpcEndpointHostedZoneId,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessApplicationProperties
type SamtranslatorInternalSchemaSourceAwsServerlessApplicationProperties struct {
	Location         interface{} `json:"Location"`
	NotificationARNs interface{} `json:"NotificationARNs,omitempty"`
	Parameters       interface{} `json:"Parameters,omitempty"`
	Tags             *Tags       `json:"Tags,omitempty"`
	TimeoutInMinutes interface{} `json:"TimeoutInMinutes,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessApplicationResource
type SamtranslatorInternalSchemaSourceAwsServerlessApplicationResource struct {
	Condition           interface{}                                                          `json:"Condition,omitempty"`
	DeletionPolicy      interface{}                                                          `json:"DeletionPolicy,omitempty"`
	DependsOn           interface{}                                                          `json:"DependsOn,omitempty"`
	IgnoreGlobals       interface{}                                                          `json:"IgnoreGlobals,omitempty"`
	Metadata            interface{}                                                          `json:"Metadata,omitempty"`
	Properties          *SamtranslatorInternalSchemaSourceAwsServerlessApplicationProperties `json:"Properties"`
	Type                string                                                               `json:"Type"`
	UpdateReplacePolicy interface{}                                                          `json:"UpdateReplacePolicy,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessCapacityProviderGlobals
type SamtranslatorInternalSchemaSourceAwsServerlessCapacityProviderGlobals struct {
	InstanceRequirements interface{} `json:"InstanceRequirements,omitempty"`
	KmsKeyArn            interface{} `json:"KmsKeyArn,omitempty"`
	OperatorRole         interface{} `json:"OperatorRole,omitempty"`
	PropagateTags        bool        `json:"PropagateTags,omitempty"`
	ScalingConfig        interface{} `json:"ScalingConfig,omitempty"`
	Tags                 *Tags       `json:"Tags,omitempty"`
	VpcConfig            interface{} `json:"VpcConfig,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessCapacityProviderProperties
type SamtranslatorInternalSchemaSourceAwsServerlessCapacityProviderProperties struct {
	CapacityProviderName interface{} `json:"CapacityProviderName,omitempty"`
	InstanceRequirements interface{} `json:"InstanceRequirements,omitempty"`
	KmsKeyArn            interface{} `json:"KmsKeyArn,omitempty"`
	OperatorRole         interface{} `json:"OperatorRole,omitempty"`
	PropagateTags        bool        `json:"PropagateTags,omitempty"`
	ScalingConfig        interface{} `json:"ScalingConfig,omitempty"`
	Tags                 *Tags       `json:"Tags,omitempty"`
	VpcConfig            interface{} `json:"VpcConfig"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessCapacityProviderResource
type SamtranslatorInternalSchemaSourceAwsServerlessCapacityProviderResource struct {
	Condition           interface{} `json:"Condition,omitempty"`
	DeletionPolicy      interface{} `json:"DeletionPolicy,omitempty"`
	DependsOn           interface{} `json:"DependsOn,omitempty"`
	IgnoreGlobals       interface{} `json:"IgnoreGlobals,omitempty"`
	Metadata            interface{} `json:"Metadata,omitempty"`
	Properties          *Properties `json:"Properties"`
	Type                string      `json:"Type"`
	UpdateReplacePolicy interface{} `json:"UpdateReplacePolicy,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessConnectorProperties
type SamtranslatorInternalSchemaSourceAwsServerlessConnectorProperties struct {
	Destination interface{} `json:"Destination"`
	Permissions []string    `json:"Permissions"`
	Source      interface{} `json:"Source"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessConnectorResource
type SamtranslatorInternalSchemaSourceAwsServerlessConnectorResource struct {
	Condition           interface{} `json:"Condition,omitempty"`
	DeletionPolicy      interface{} `json:"DeletionPolicy,omitempty"`
	DependsOn           interface{} `json:"DependsOn,omitempty"`
	IgnoreGlobals       interface{} `json:"IgnoreGlobals,omitempty"`
	Metadata            interface{} `json:"Metadata,omitempty"`
	Properties          *Properties `json:"Properties"`
	Type                string      `json:"Type"`
	UpdateReplacePolicy interface{} `json:"UpdateReplacePolicy,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessFunctionApiEvent
type SamtranslatorInternalSchemaSourceAwsServerlessFunctionApiEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessFunctionApiEventProperties
type SamtranslatorInternalSchemaSourceAwsServerlessFunctionApiEventProperties struct {
	Auth              interface{}   `json:"Auth,omitempty"`
	Method            string        `json:"Method"`
	Path              string        `json:"Path"`
	RequestModel      interface{}   `json:"RequestModel,omitempty"`
	RequestParameters []interface{} `json:"RequestParameters,omitempty"`
	RestApiId         interface{}   `json:"RestApiId,omitempty"`
	TimeoutInMillis   interface{}   `json:"TimeoutInMillis,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessFunctionCloudWatchEvent
type SamtranslatorInternalSchemaSourceAwsServerlessFunctionCloudWatchEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessFunctionCloudWatchEventProperties
type SamtranslatorInternalSchemaSourceAwsServerlessFunctionCloudWatchEventProperties struct {
	Enabled      bool        `json:"Enabled,omitempty"`
	EventBusName interface{} `json:"EventBusName,omitempty"`
	Input        interface{} `json:"Input,omitempty"`
	InputPath    interface{} `json:"InputPath,omitempty"`
	Pattern      interface{} `json:"Pattern,omitempty"`
	State        interface{} `json:"State,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessFunctionDeadLetterConfig
type SamtranslatorInternalSchemaSourceAwsServerlessFunctionDeadLetterConfig struct {
	Arn            interface{} `json:"Arn,omitempty"`
	QueueLogicalId string      `json:"QueueLogicalId,omitempty"`
	Type           string      `json:"Type,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessFunctionEventBridgeRuleEvent
type SamtranslatorInternalSchemaSourceAwsServerlessFunctionEventBridgeRuleEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessFunctionEventBridgeRuleEventProperties
type SamtranslatorInternalSchemaSourceAwsServerlessFunctionEventBridgeRuleEventProperties struct {
	DeadLetterConfig interface{} `json:"DeadLetterConfig,omitempty"`
	EventBusName     interface{} `json:"EventBusName,omitempty"`
	Input            interface{} `json:"Input,omitempty"`
	InputPath        interface{} `json:"InputPath,omitempty"`
	InputTransformer interface{} `json:"InputTransformer,omitempty"`
	Pattern          interface{} `json:"Pattern"`
	RetryPolicy      interface{} `json:"RetryPolicy,omitempty"`
	RuleName         interface{} `json:"RuleName,omitempty"`
	Target           interface{} `json:"Target,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessFunctionEventBridgeRuleTarget
type SamtranslatorInternalSchemaSourceAwsServerlessFunctionEventBridgeRuleTarget struct {
	Id interface{} `json:"Id"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessFunctionGlobals
type SamtranslatorInternalSchemaSourceAwsServerlessFunctionGlobals struct {
	Architectures                interface{}               `json:"Architectures,omitempty"`
	AssumeRolePolicyDocument     *AssumeRolePolicyDocument `json:"AssumeRolePolicyDocument,omitempty"`
	AutoPublishAlias             interface{}               `json:"AutoPublishAlias,omitempty"`
	CapacityProviderConfig       interface{}               `json:"CapacityProviderConfig,omitempty"`
	CodeUri                      interface{}               `json:"CodeUri,omitempty"`
	DeadLetterQueue              interface{}               `json:"DeadLetterQueue,omitempty"`
	DeploymentPreference         interface{}               `json:"DeploymentPreference,omitempty"`
	Description                  interface{}               `json:"Description,omitempty"`
	DurableConfig                interface{}               `json:"DurableConfig,omitempty"`
	Environment                  interface{}               `json:"Environment,omitempty"`
	EphemeralStorage             interface{}               `json:"EphemeralStorage,omitempty"`
	EventInvokeConfig            interface{}               `json:"EventInvokeConfig,omitempty"`
	FunctionScalingConfig        interface{}               `json:"FunctionScalingConfig,omitempty"`
	Handler                      interface{}               `json:"Handler,omitempty"`
	KmsKeyArn                    interface{}               `json:"KmsKeyArn,omitempty"`
	Layers                       interface{}               `json:"Layers,omitempty"`
	LoggingConfig                interface{}               `json:"LoggingConfig,omitempty"`
	MemorySize                   interface{}               `json:"MemorySize,omitempty"`
	PermissionsBoundary          interface{}               `json:"PermissionsBoundary,omitempty"`
	PropagateTags                bool                      `json:"PropagateTags,omitempty"`
	ProvisionedConcurrencyConfig interface{}               `json:"ProvisionedConcurrencyConfig,omitempty"`
	PublishToLatestPublished     interface{}               `json:"PublishToLatestPublished,omitempty"`
	RecursiveLoop                interface{}               `json:"RecursiveLoop,omitempty"`
	ReservedConcurrentExecutions interface{}               `json:"ReservedConcurrentExecutions,omitempty"`
	RolePath                     interface{}               `json:"RolePath,omitempty"`
	Runtime                      interface{}               `json:"Runtime,omitempty"`
	RuntimeManagementConfig      interface{}               `json:"RuntimeManagementConfig,omitempty"`
	SnapStart                    interface{}               `json:"SnapStart,omitempty"`
	SourceKMSKeyArn              interface{}               `json:"SourceKMSKeyArn,omitempty"`
	Tags                         *Tags                     `json:"Tags,omitempty"`
	TenancyConfig                interface{}               `json:"TenancyConfig,omitempty"`
	Timeout                      interface{}               `json:"Timeout,omitempty"`
	Tracing                      interface{}               `json:"Tracing,omitempty"`
	VersionDeletionPolicy        interface{}               `json:"VersionDeletionPolicy,omitempty"`
	VpcConfig                    interface{}               `json:"VpcConfig,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessFunctionProperties
type SamtranslatorInternalSchemaSourceAwsServerlessFunctionProperties struct {
	Architectures                 interface{}               `json:"Architectures,omitempty"`
	AssumeRolePolicyDocument      *AssumeRolePolicyDocument `json:"AssumeRolePolicyDocument,omitempty"`
	AutoPublishAlias              interface{}               `json:"AutoPublishAlias,omitempty"`
	AutoPublishAliasAllProperties bool                      `json:"AutoPublishAliasAllProperties,omitempty"`
	AutoPublishCodeSha256         interface{}               `json:"AutoPublishCodeSha256,omitempty"`
	CapacityProviderConfig        interface{}               `json:"CapacityProviderConfig,omitempty"`
	CodeSigningConfigArn          interface{}               `json:"CodeSigningConfigArn,omitempty"`
	CodeUri                       interface{}               `json:"CodeUri,omitempty"`
	DeadLetterQueue               interface{}               `json:"DeadLetterQueue,omitempty"`
	DeploymentPreference          interface{}               `json:"DeploymentPreference,omitempty"`
	Description                   interface{}               `json:"Description,omitempty"`
	DurableConfig                 interface{}               `json:"DurableConfig,omitempty"`
	Environment                   interface{}               `json:"Environment,omitempty"`
	EphemeralStorage              interface{}               `json:"EphemeralStorage,omitempty"`
	EventInvokeConfig             interface{}               `json:"EventInvokeConfig,omitempty"`
	Events                        map[string]interface{}    `json:"Events,omitempty"`
	FileSystemConfigs             interface{}               `json:"FileSystemConfigs,omitempty"`
	FunctionName                  interface{}               `json:"FunctionName,omitempty"`
	FunctionScalingConfig         interface{}               `json:"FunctionScalingConfig,omitempty"`
	FunctionUrlConfig             interface{}               `json:"FunctionUrlConfig,omitempty"`
	Handler                       interface{}               `json:"Handler,omitempty"`
	ImageConfig                   interface{}               `json:"ImageConfig,omitempty"`
	ImageUri                      interface{}               `json:"ImageUri,omitempty"`
	InlineCode                    interface{}               `json:"InlineCode,omitempty"`
	KmsKeyArn                     interface{}               `json:"KmsKeyArn,omitempty"`
	Layers                        interface{}               `json:"Layers,omitempty"`
	LoggingConfig                 interface{}               `json:"LoggingConfig,omitempty"`
	MemorySize                    interface{}               `json:"MemorySize,omitempty"`
	PackageType                   interface{}               `json:"PackageType,omitempty"`
	PermissionsBoundary           interface{}               `json:"PermissionsBoundary,omitempty"`
	Policies                      interface{}               `json:"Policies,omitempty"`
	PropagateTags                 bool                      `json:"PropagateTags,omitempty"`
	ProvisionedConcurrencyConfig  interface{}               `json:"ProvisionedConcurrencyConfig,omitempty"`
	PublishToLatestPublished      interface{}               `json:"PublishToLatestPublished,omitempty"`
	RecursiveLoop                 interface{}               `json:"RecursiveLoop,omitempty"`
	ReservedConcurrentExecutions  interface{}               `json:"ReservedConcurrentExecutions,omitempty"`
	Role                          interface{}               `json:"Role,omitempty"`
	RolePath                      interface{}               `json:"RolePath,omitempty"`
	Runtime                       interface{}               `json:"Runtime,omitempty"`
	RuntimeManagementConfig       interface{}               `json:"RuntimeManagementConfig,omitempty"`
	SnapStart                     interface{}               `json:"SnapStart,omitempty"`
	SourceKMSKeyArn               interface{}               `json:"SourceKMSKeyArn,omitempty"`
	Tags                          *Tags                     `json:"Tags,omitempty"`
	TenancyConfig                 interface{}               `json:"TenancyConfig,omitempty"`
	Timeout                       interface{}               `json:"Timeout,omitempty"`
	Tracing                       interface{}               `json:"Tracing,omitempty"`
	VersionDeletionPolicy         interface{}               `json:"VersionDeletionPolicy,omitempty"`
	VersionDescription            interface{}               `json:"VersionDescription,omitempty"`
	VpcConfig                     interface{}               `json:"VpcConfig,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessFunctionResource
type SamtranslatorInternalSchemaSourceAwsServerlessFunctionResource struct {
	Condition           interface{}                                                       `json:"Condition,omitempty"`
	Connectors          map[string]*EmbeddedConnector                                     `json:"Connectors,omitempty"`
	DeletionPolicy      interface{}                                                       `json:"DeletionPolicy,omitempty"`
	DependsOn           interface{}                                                       `json:"DependsOn,omitempty"`
	IgnoreGlobals       interface{}                                                       `json:"IgnoreGlobals,omitempty"`
	Metadata            interface{}                                                       `json:"Metadata,omitempty"`
	Properties          *SamtranslatorInternalSchemaSourceAwsServerlessFunctionProperties `json:"Properties,omitempty"`
	Type                string                                                            `json:"Type"`
	UpdateReplacePolicy interface{}                                                       `json:"UpdateReplacePolicy,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessFunctionResourcePolicy
type SamtranslatorInternalSchemaSourceAwsServerlessFunctionResourcePolicy struct {
	AwsAccountBlacklist    []interface{} `json:"AwsAccountBlacklist,omitempty"`
	AwsAccountWhitelist    []interface{} `json:"AwsAccountWhitelist,omitempty"`
	CustomStatements       []interface{} `json:"CustomStatements,omitempty"`
	IntrinsicVpcBlacklist  []interface{} `json:"IntrinsicVpcBlacklist,omitempty"`
	IntrinsicVpcWhitelist  []interface{} `json:"IntrinsicVpcWhitelist,omitempty"`
	IntrinsicVpceBlacklist []interface{} `json:"IntrinsicVpceBlacklist,omitempty"`
	IntrinsicVpceWhitelist []interface{} `json:"IntrinsicVpceWhitelist,omitempty"`
	IpRangeBlacklist       []interface{} `json:"IpRangeBlacklist,omitempty"`
	IpRangeWhitelist       []interface{} `json:"IpRangeWhitelist,omitempty"`
	SourceVpcBlacklist     []interface{} `json:"SourceVpcBlacklist,omitempty"`
	SourceVpcWhitelist     []interface{} `json:"SourceVpcWhitelist,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessFunctionScheduleEvent
type SamtranslatorInternalSchemaSourceAwsServerlessFunctionScheduleEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessFunctionScheduleV2Event
type SamtranslatorInternalSchemaSourceAwsServerlessFunctionScheduleV2Event struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessFunctionScheduleV2EventProperties
type SamtranslatorInternalSchemaSourceAwsServerlessFunctionScheduleV2EventProperties struct {
	DeadLetterConfig           interface{} `json:"DeadLetterConfig,omitempty"`
	Description                interface{} `json:"Description,omitempty"`
	EndDate                    interface{} `json:"EndDate,omitempty"`
	FlexibleTimeWindow         interface{} `json:"FlexibleTimeWindow,omitempty"`
	GroupName                  interface{} `json:"GroupName,omitempty"`
	Input                      interface{} `json:"Input,omitempty"`
	KmsKeyArn                  interface{} `json:"KmsKeyArn,omitempty"`
	Name                       interface{} `json:"Name,omitempty"`
	OmitName                   bool        `json:"OmitName,omitempty"`
	PermissionsBoundary        interface{} `json:"PermissionsBoundary,omitempty"`
	RetryPolicy                interface{} `json:"RetryPolicy,omitempty"`
	RoleArn                    interface{} `json:"RoleArn,omitempty"`
	ScheduleExpression         interface{} `json:"ScheduleExpression,omitempty"`
	ScheduleExpressionTimezone interface{} `json:"ScheduleExpressionTimezone,omitempty"`
	StartDate                  interface{} `json:"StartDate,omitempty"`
	State                      interface{} `json:"State,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessGraphqlapiAuth
type SamtranslatorInternalSchemaSourceAwsServerlessGraphqlapiAuth struct {
	Additional       []Authorizer            `json:"Additional,omitempty"`
	LambdaAuthorizer *LambdaAuthorizerConfig `json:"LambdaAuthorizer,omitempty"`
	OpenIDConnect    *OpenIDConnectConfig    `json:"OpenIDConnect,omitempty"`
	Type             string                  `json:"Type"`
	UserPool         *UserPoolConfig         `json:"UserPool,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessGraphqlapiProperties
type SamtranslatorInternalSchemaSourceAwsServerlessGraphqlapiProperties struct {
	ApiKeys             map[string]*ApiKey              `json:"ApiKeys,omitempty"`
	Auth                *Auth                           `json:"Auth"`
	Cache               *Cache                          `json:"Cache,omitempty"`
	DataSources         *DataSources                    `json:"DataSources,omitempty"`
	DomainName          *DomainName                     `json:"DomainName,omitempty"`
	Functions           map[string]*Function            `json:"Functions,omitempty"`
	IntrospectionConfig interface{}                     `json:"IntrospectionConfig,omitempty"`
	Logging             interface{}                     `json:"Logging,omitempty"`
	Name                interface{}                     `json:"Name,omitempty"`
	OwnerContact        interface{}                     `json:"OwnerContact,omitempty"`
	QueryDepthLimit     interface{}                     `json:"QueryDepthLimit,omitempty"`
	ResolverCountLimit  interface{}                     `json:"ResolverCountLimit,omitempty"`
	Resolvers           map[string]map[string]*Resolver `json:"Resolvers,omitempty"`
	SchemaInline        interface{}                     `json:"SchemaInline,omitempty"`
	SchemaUri           interface{}                     `json:"SchemaUri,omitempty"`
	Tags                *Tags                           `json:"Tags,omitempty"`
	Visibility          interface{}                     `json:"Visibility,omitempty"`
	XrayEnabled         bool                            `json:"XrayEnabled,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessGraphqlapiResource
type SamtranslatorInternalSchemaSourceAwsServerlessGraphqlapiResource struct {
	Properties *Properties `json:"Properties"`
	Type       string      `json:"Type"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessHttpapiAuth
type SamtranslatorInternalSchemaSourceAwsServerlessHttpapiAuth struct {
	Authorizers         map[string]interface{} `json:"Authorizers,omitempty"`
	DefaultAuthorizer   string                 `json:"DefaultAuthorizer,omitempty"`
	EnableIamAuthorizer bool                   `json:"EnableIamAuthorizer,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessHttpapiDefinitionUri
type SamtranslatorInternalSchemaSourceAwsServerlessHttpapiDefinitionUri struct {
	Bucket  string `json:"Bucket"`
	Key     string `json:"Key"`
	Version string `json:"Version,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessHttpapiDomain
type SamtranslatorInternalSchemaSourceAwsServerlessHttpapiDomain struct {
	BasePath                            []string    `json:"BasePath,omitempty"`
	CertificateArn                      interface{} `json:"CertificateArn"`
	DomainName                          interface{} `json:"DomainName"`
	EndpointConfiguration               interface{} `json:"EndpointConfiguration,omitempty"`
	MutualTlsAuthentication             interface{} `json:"MutualTlsAuthentication,omitempty"`
	OwnershipVerificationCertificateArn interface{} `json:"OwnershipVerificationCertificateArn,omitempty"`
	Route53                             interface{} `json:"Route53,omitempty"`
	SecurityPolicy                      interface{} `json:"SecurityPolicy,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessHttpapiGlobals
type SamtranslatorInternalSchemaSourceAwsServerlessHttpapiGlobals struct {
	AccessLogSettings    interface{} `json:"AccessLogSettings,omitempty"`
	Auth                 interface{} `json:"Auth,omitempty"`
	CorsConfiguration    interface{} `json:"CorsConfiguration,omitempty"`
	DefaultRouteSettings interface{} `json:"DefaultRouteSettings,omitempty"`
	Domain               interface{} `json:"Domain,omitempty"`
	FailOnWarnings       interface{} `json:"FailOnWarnings,omitempty"`
	PropagateTags        bool        `json:"PropagateTags,omitempty"`
	RouteSettings        interface{} `json:"RouteSettings,omitempty"`
	StageVariables       interface{} `json:"StageVariables,omitempty"`
	Tags                 *Tags       `json:"Tags,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessHttpapiProperties
type SamtranslatorInternalSchemaSourceAwsServerlessHttpapiProperties struct {
	AccessLogSettings         interface{}     `json:"AccessLogSettings,omitempty"`
	Auth                      interface{}     `json:"Auth,omitempty"`
	CorsConfiguration         interface{}     `json:"CorsConfiguration,omitempty"`
	DefaultRouteSettings      interface{}     `json:"DefaultRouteSettings,omitempty"`
	DefinitionBody            *DefinitionBody `json:"DefinitionBody,omitempty"`
	DefinitionUri             interface{}     `json:"DefinitionUri,omitempty"`
	Description               string          `json:"Description,omitempty"`
	DisableExecuteApiEndpoint interface{}     `json:"DisableExecuteApiEndpoint,omitempty"`
	Domain                    interface{}     `json:"Domain,omitempty"`
	FailOnWarnings            interface{}     `json:"FailOnWarnings,omitempty"`
	Name                      interface{}     `json:"Name,omitempty"`
	PropagateTags             bool            `json:"PropagateTags,omitempty"`
	RouteSettings             interface{}     `json:"RouteSettings,omitempty"`
	StageName                 interface{}     `json:"StageName,omitempty"`
	StageVariables            interface{}     `json:"StageVariables,omitempty"`
	Tags                      *Tags           `json:"Tags,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessHttpapiResource
type SamtranslatorInternalSchemaSourceAwsServerlessHttpapiResource struct {
	Condition           interface{}                                                      `json:"Condition,omitempty"`
	Connectors          map[string]*EmbeddedConnector                                    `json:"Connectors,omitempty"`
	DeletionPolicy      interface{}                                                      `json:"DeletionPolicy,omitempty"`
	DependsOn           interface{}                                                      `json:"DependsOn,omitempty"`
	IgnoreGlobals       interface{}                                                      `json:"IgnoreGlobals,omitempty"`
	Metadata            interface{}                                                      `json:"Metadata,omitempty"`
	Properties          *SamtranslatorInternalSchemaSourceAwsServerlessHttpapiProperties `json:"Properties,omitempty"`
	Type                string                                                           `json:"Type"`
	UpdateReplacePolicy interface{}                                                      `json:"UpdateReplacePolicy,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessHttpapiRoute53
type SamtranslatorInternalSchemaSourceAwsServerlessHttpapiRoute53 struct {
	DistributionDomainName interface{} `json:"DistributionDomainName,omitempty"`
	EvaluateTargetHealth   interface{} `json:"EvaluateTargetHealth,omitempty"`
	HostedZoneId           interface{} `json:"HostedZoneId,omitempty"`
	HostedZoneName         interface{} `json:"HostedZoneName,omitempty"`
	IpV6                   bool        `json:"IpV6,omitempty"`
	Region                 interface{} `json:"Region,omitempty"`
	SetIdentifier          interface{} `json:"SetIdentifier,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessLayerversionGlobals
type SamtranslatorInternalSchemaSourceAwsServerlessLayerversionGlobals struct {
	PublishLambdaVersion bool `json:"PublishLambdaVersion,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessLayerversionProperties
type SamtranslatorInternalSchemaSourceAwsServerlessLayerversionProperties struct {
	CompatibleArchitectures interface{} `json:"CompatibleArchitectures,omitempty"`
	CompatibleRuntimes      interface{} `json:"CompatibleRuntimes,omitempty"`
	ContentUri              interface{} `json:"ContentUri"`
	Description             interface{} `json:"Description,omitempty"`
	LayerName               interface{} `json:"LayerName,omitempty"`
	LicenseInfo             interface{} `json:"LicenseInfo,omitempty"`
	PublishLambdaVersion    bool        `json:"PublishLambdaVersion,omitempty"`
	RetentionPolicy         interface{} `json:"RetentionPolicy,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessLayerversionResource
type SamtranslatorInternalSchemaSourceAwsServerlessLayerversionResource struct {
	Condition           interface{} `json:"Condition,omitempty"`
	DeletionPolicy      interface{} `json:"DeletionPolicy,omitempty"`
	DependsOn           interface{} `json:"DependsOn,omitempty"`
	IgnoreGlobals       interface{} `json:"IgnoreGlobals,omitempty"`
	Metadata            interface{} `json:"Metadata,omitempty"`
	Properties          *Properties `json:"Properties"`
	Type                string      `json:"Type"`
	UpdateReplacePolicy interface{} `json:"UpdateReplacePolicy,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessSimpletableGlobals
type SamtranslatorInternalSchemaSourceAwsServerlessSimpletableGlobals struct {
	SSESpecification interface{} `json:"SSESpecification,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessSimpletableProperties
type SamtranslatorInternalSchemaSourceAwsServerlessSimpletableProperties struct {
	PointInTimeRecoverySpecification interface{} `json:"PointInTimeRecoverySpecification,omitempty"`
	PrimaryKey                       interface{} `json:"PrimaryKey,omitempty"`
	ProvisionedThroughput            interface{} `json:"ProvisionedThroughput,omitempty"`
	SSESpecification                 interface{} `json:"SSESpecification,omitempty"`
	TableName                        interface{} `json:"TableName,omitempty"`
	Tags                             *Tags       `json:"Tags,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessSimpletableResource
type SamtranslatorInternalSchemaSourceAwsServerlessSimpletableResource struct {
	Condition           interface{}                   `json:"Condition,omitempty"`
	Connectors          map[string]*EmbeddedConnector `json:"Connectors,omitempty"`
	DeletionPolicy      interface{}                   `json:"DeletionPolicy,omitempty"`
	DependsOn           interface{}                   `json:"DependsOn,omitempty"`
	IgnoreGlobals       interface{}                   `json:"IgnoreGlobals,omitempty"`
	Metadata            interface{}                   `json:"Metadata,omitempty"`
	Properties          *Properties                   `json:"Properties,omitempty"`
	Type                string                        `json:"Type"`
	UpdateReplacePolicy interface{}                   `json:"UpdateReplacePolicy,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessStatemachineApiEvent
type SamtranslatorInternalSchemaSourceAwsServerlessStatemachineApiEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessStatemachineApiEventProperties
type SamtranslatorInternalSchemaSourceAwsServerlessStatemachineApiEventProperties struct {
	Auth                    interface{} `json:"Auth,omitempty"`
	Method                  string      `json:"Method"`
	Path                    string      `json:"Path"`
	RestApiId               interface{} `json:"RestApiId,omitempty"`
	UnescapeMappingTemplate bool        `json:"UnescapeMappingTemplate,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessStatemachineAuth
type SamtranslatorInternalSchemaSourceAwsServerlessStatemachineAuth struct {
	ApiKeyRequired      bool        `json:"ApiKeyRequired,omitempty"`
	AuthorizationScopes []string    `json:"AuthorizationScopes,omitempty"`
	Authorizer          string      `json:"Authorizer,omitempty"`
	ResourcePolicy      interface{} `json:"ResourcePolicy,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessStatemachineCloudWatchEvent
type SamtranslatorInternalSchemaSourceAwsServerlessStatemachineCloudWatchEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessStatemachineCloudWatchEventProperties
type SamtranslatorInternalSchemaSourceAwsServerlessStatemachineCloudWatchEventProperties struct {
	EventBusName interface{} `json:"EventBusName,omitempty"`
	Input        interface{} `json:"Input,omitempty"`
	InputPath    interface{} `json:"InputPath,omitempty"`
	Pattern      interface{} `json:"Pattern,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessStatemachineDeadLetterConfig
type SamtranslatorInternalSchemaSourceAwsServerlessStatemachineDeadLetterConfig struct {
	Arn            interface{} `json:"Arn,omitempty"`
	QueueLogicalId string      `json:"QueueLogicalId,omitempty"`
	Type           string      `json:"Type,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessStatemachineEventBridgeRuleEvent
type SamtranslatorInternalSchemaSourceAwsServerlessStatemachineEventBridgeRuleEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessStatemachineEventBridgeRuleEventProperties
type SamtranslatorInternalSchemaSourceAwsServerlessStatemachineEventBridgeRuleEventProperties struct {
	DeadLetterConfig interface{} `json:"DeadLetterConfig,omitempty"`
	EventBusName     interface{} `json:"EventBusName,omitempty"`
	Input            interface{} `json:"Input,omitempty"`
	InputPath        interface{} `json:"InputPath,omitempty"`
	InputTransformer interface{} `json:"InputTransformer,omitempty"`
	Pattern          interface{} `json:"Pattern,omitempty"`
	RetryPolicy      interface{} `json:"RetryPolicy,omitempty"`
	RuleName         interface{} `json:"RuleName,omitempty"`
	Target           interface{} `json:"Target,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessStatemachineEventBridgeRuleTarget
type SamtranslatorInternalSchemaSourceAwsServerlessStatemachineEventBridgeRuleTarget struct {
	Id interface{} `json:"Id"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessStatemachineGlobals
type SamtranslatorInternalSchemaSourceAwsServerlessStatemachineGlobals struct {
	PropagateTags bool `json:"PropagateTags,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessStatemachineProperties
type SamtranslatorInternalSchemaSourceAwsServerlessStatemachineProperties struct {
	AutoPublishAlias        interface{}              `json:"AutoPublishAlias,omitempty"`
	Definition              *Definition              `json:"Definition,omitempty"`
	DefinitionSubstitutions *DefinitionSubstitutions `json:"DefinitionSubstitutions,omitempty"`
	DefinitionUri           interface{}              `json:"DefinitionUri,omitempty"`
	DeploymentPreference    interface{}              `json:"DeploymentPreference,omitempty"`
	Events                  map[string]interface{}   `json:"Events,omitempty"`
	Logging                 interface{}              `json:"Logging,omitempty"`
	Name                    interface{}              `json:"Name,omitempty"`
	PermissionsBoundary     interface{}              `json:"PermissionsBoundary,omitempty"`
	Policies                interface{}              `json:"Policies,omitempty"`
	PropagateTags           bool                     `json:"PropagateTags,omitempty"`
	Role                    interface{}              `json:"Role,omitempty"`
	RolePath                interface{}              `json:"RolePath,omitempty"`
	Tags                    *Tags                    `json:"Tags,omitempty"`
	Tracing                 interface{}              `json:"Tracing,omitempty"`
	Type                    interface{}              `json:"Type,omitempty"`
	UseAliasAsEventTarget   bool                     `json:"UseAliasAsEventTarget,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessStatemachineResource
type SamtranslatorInternalSchemaSourceAwsServerlessStatemachineResource struct {
	Condition           interface{}                   `json:"Condition,omitempty"`
	Connectors          map[string]*EmbeddedConnector `json:"Connectors,omitempty"`
	DeletionPolicy      interface{}                   `json:"DeletionPolicy,omitempty"`
	DependsOn           interface{}                   `json:"DependsOn,omitempty"`
	IgnoreGlobals       interface{}                   `json:"IgnoreGlobals,omitempty"`
	Metadata            interface{}                   `json:"Metadata,omitempty"`
	Properties          *Properties                   `json:"Properties"`
	Type                string                        `json:"Type"`
	UpdateReplacePolicy interface{}                   `json:"UpdateReplacePolicy,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessStatemachineResourcePolicy
type SamtranslatorInternalSchemaSourceAwsServerlessStatemachineResourcePolicy struct {
	AwsAccountBlacklist    []interface{} `json:"AwsAccountBlacklist,omitempty"`
	AwsAccountWhitelist    []interface{} `json:"AwsAccountWhitelist,omitempty"`
	CustomStatements       []interface{} `json:"CustomStatements,omitempty"`
	IntrinsicVpcBlacklist  []interface{} `json:"IntrinsicVpcBlacklist,omitempty"`
	IntrinsicVpcWhitelist  []interface{} `json:"IntrinsicVpcWhitelist,omitempty"`
	IntrinsicVpceBlacklist []interface{} `json:"IntrinsicVpceBlacklist,omitempty"`
	IntrinsicVpceWhitelist []interface{} `json:"IntrinsicVpceWhitelist,omitempty"`
	IpRangeBlacklist       []interface{} `json:"IpRangeBlacklist,omitempty"`
	IpRangeWhitelist       []interface{} `json:"IpRangeWhitelist,omitempty"`
	SourceVpcBlacklist     []interface{} `json:"SourceVpcBlacklist,omitempty"`
	SourceVpcWhitelist     []interface{} `json:"SourceVpcWhitelist,omitempty"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessStatemachineScheduleEvent
type SamtranslatorInternalSchemaSourceAwsServerlessStatemachineScheduleEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessStatemachineScheduleV2Event
type SamtranslatorInternalSchemaSourceAwsServerlessStatemachineScheduleV2Event struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// SamtranslatorInternalSchemaSourceAwsServerlessStatemachineScheduleV2EventProperties
type SamtranslatorInternalSchemaSourceAwsServerlessStatemachineScheduleV2EventProperties struct {
	DeadLetterConfig           interface{} `json:"DeadLetterConfig,omitempty"`
	Description                interface{} `json:"Description,omitempty"`
	EndDate                    interface{} `json:"EndDate,omitempty"`
	FlexibleTimeWindow         interface{} `json:"FlexibleTimeWindow,omitempty"`
	GroupName                  interface{} `json:"GroupName,omitempty"`
	Input                      interface{} `json:"Input,omitempty"`
	KmsKeyArn                  interface{} `json:"KmsKeyArn,omitempty"`
	Name                       interface{} `json:"Name,omitempty"`
	OmitName                   bool        `json:"OmitName,omitempty"`
	PermissionsBoundary        interface{} `json:"PermissionsBoundary,omitempty"`
	RetryPolicy                interface{} `json:"RetryPolicy,omitempty"`
	RoleArn                    interface{} `json:"RoleArn,omitempty"`
	ScheduleExpression         interface{} `json:"ScheduleExpression,omitempty"`
	ScheduleExpressionTimezone interface{} `json:"ScheduleExpressionTimezone,omitempty"`
	StartDate                  interface{} `json:"StartDate,omitempty"`
	State                      interface{} `json:"State,omitempty"`
}

// ScalingConfig
type ScalingConfig struct {
	AverageCPUUtilization interface{} `json:"AverageCPUUtilization,omitempty"`
	MaxVCpuCount          interface{} `json:"MaxVCpuCount,omitempty"`
}

// ScheduleEventProperties
type ScheduleEventProperties struct {
	DeadLetterConfig interface{} `json:"DeadLetterConfig,omitempty"`
	Description      interface{} `json:"Description,omitempty"`
	Enabled          bool        `json:"Enabled,omitempty"`
	Input            interface{} `json:"Input,omitempty"`
	Name             interface{} `json:"Name,omitempty"`
	RetryPolicy      interface{} `json:"RetryPolicy,omitempty"`
	RoleArn          interface{} `json:"RoleArn,omitempty"`
	Schedule         interface{} `json:"Schedule,omitempty"`
	State            interface{} `json:"State,omitempty"`
	Target           interface{} `json:"Target,omitempty"`
}

// ScheduleTarget
type ScheduleTarget struct {
	Id interface{} `json:"Id"`
}

// SelfManagedKafkaEvent
type SelfManagedKafkaEvent struct {
	Properties interface{} `json:"Properties"`
	Type       string      `json:"Type"`
}

// SelfManagedKafkaEventProperties
type SelfManagedKafkaEventProperties struct {
	BatchSize                  interface{}   `json:"BatchSize,omitempty"`
	BisectBatchOnFunctionError interface{}   `json:"BisectBatchOnFunctionError,omitempty"`
	ConsumerGroupId            interface{}   `json:"ConsumerGroupId,omitempty"`
	Enabled                    interface{}   `json:"Enabled,omitempty"`
	FilterCriteria             interface{}   `json:"FilterCriteria,omitempty"`
	FunctionResponseTypes      interface{}   `json:"FunctionResponseTypes,omitempty"`
	KafkaBootstrapServers      []interface{} `json:"KafkaBootstrapServers,omitempty"`
	KmsKeyArn                  interface{}   `json:"KmsKeyArn,omitempty"`
	MaximumRecordAgeInSeconds  interface{}   `json:"MaximumRecordAgeInSeconds,omitempty"`
	MaximumRetryAttempts       interface{}   `json:"MaximumRetryAttempts,omitempty"`
	ProvisionedPollerConfig    interface{}   `json:"ProvisionedPollerConfig,omitempty"`
	SchemaRegistryConfig       interface{}   `json:"SchemaRegistryConfig,omitempty"`
	SourceAccessConfigurations interface{}   `json:"SourceAccessConfigurations"`
	StartingPosition           interface{}   `json:"StartingPosition,omitempty"`
	StartingPositionTimestamp  interface{}   `json:"StartingPositionTimestamp,omitempty"`
	Topics                     interface{}   `json:"Topics"`
}

// SourceReferenceProperties
type SourceReferenceProperties struct {
	Qualifier interface{} `json:"Qualifier,omitempty"`
}

// SqsSubscription
type SqsSubscription struct {
	BatchSize            interface{} `json:"BatchSize,omitempty"`
	Enabled              bool        `json:"Enabled,omitempty"`
	QueueArn             interface{} `json:"QueueArn"`
	QueuePolicyLogicalId string      `json:"QueuePolicyLogicalId,omitempty"`
	QueueUrl             interface{} `json:"QueueUrl"`
}

// Sync
type Sync struct {
	ConflictDetection           interface{}                  `json:"ConflictDetection"`
	ConflictHandler             interface{}                  `json:"ConflictHandler,omitempty"`
	LambdaConflictHandlerConfig *LambdaConflictHandlerConfig `json:"LambdaConflictHandlerConfig,omitempty"`
}

// Tags
type Tags struct{}

// UsagePlan
type UsagePlan struct {
	CreateUsagePlan interface{} `json:"CreateUsagePlan"`
	Description     interface{} `json:"Description,omitempty"`
	Quota           interface{} `json:"Quota,omitempty"`
	Tags            interface{} `json:"Tags,omitempty"`
	Throttle        interface{} `json:"Throttle,omitempty"`
	UsagePlanName   interface{} `json:"UsagePlanName,omitempty"`
}

// UserPoolConfig
type UserPoolConfig struct {
	AppIdClientRegex interface{} `json:"AppIdClientRegex,omitempty"`
	AwsRegion        interface{} `json:"AwsRegion,omitempty"`
	DefaultAction    interface{} `json:"DefaultAction,omitempty"`
	UserPoolId       interface{} `json:"UserPoolId"`
}

// VpcConfig
type VpcConfig struct {
	SecurityGroupIds interface{} `json:"SecurityGroupIds,omitempty"`
	SubnetIds        interface{} `json:"SubnetIds"`
}
