// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import (
	"encoding/json"
	"fmt"
)

type ResourceProperties struct {
	// Architectures corresponds to the JSON schema field "Architectures".
	Architectures []string `json:"Architectures,omitempty" yaml:"Architectures,omitempty" mapstructure:"Architectures,omitempty"`

	// CodeUri corresponds to the JSON schema field "CodeUri".
	CodeUri *string `json:"CodeUri,omitempty" yaml:"CodeUri,omitempty" mapstructure:"CodeUri,omitempty"`

	// CompatibleArchitectures corresponds to the JSON schema field
	// "CompatibleArchitectures".
	CompatibleArchitectures []string `json:"CompatibleArchitectures,omitempty" yaml:"CompatibleArchitectures,omitempty" mapstructure:"CompatibleArchitectures,omitempty"`

	// ContentUri corresponds to the JSON schema field "ContentUri".
	ContentUri *string `json:"ContentUri,omitempty" yaml:"ContentUri,omitempty" mapstructure:"ContentUri,omitempty"`

	// Environment corresponds to the JSON schema field "Environment".
	Environment map[string]interface{} `json:"Environment,omitempty" yaml:"Environment,omitempty" mapstructure:"Environment,omitempty"`

	// Events corresponds to the JSON schema field "Events".
	Events map[string]interface{} `json:"Events,omitempty" yaml:"Events,omitempty" mapstructure:"Events,omitempty"`

	// FunctionName corresponds to the JSON schema field "FunctionName".
	FunctionName *string `json:"FunctionName,omitempty" yaml:"FunctionName,omitempty" mapstructure:"FunctionName,omitempty"`

	// Handler corresponds to the JSON schema field "Handler".
	Handler *string `json:"Handler,omitempty" yaml:"Handler,omitempty" mapstructure:"Handler,omitempty"`

	// LayerName corresponds to the JSON schema field "LayerName".
	LayerName *string `json:"LayerName,omitempty" yaml:"LayerName,omitempty" mapstructure:"LayerName,omitempty"`

	// Layers corresponds to the JSON schema field "Layers".
	Layers []interface{} `json:"Layers,omitempty" yaml:"Layers,omitempty" mapstructure:"Layers,omitempty"`

	// MemorySize corresponds to the JSON schema field "MemorySize".
	MemorySize *int `json:"MemorySize,omitempty" yaml:"MemorySize,omitempty" mapstructure:"MemorySize,omitempty"`

	// ProvisionedConcurrencyConfig corresponds to the JSON schema field
	// "ProvisionedConcurrencyConfig".
	ProvisionedConcurrencyConfig *ResourcePropertiesProvisionedConcurrencyConfig `json:"ProvisionedConcurrencyConfig,omitempty" yaml:"ProvisionedConcurrencyConfig,omitempty" mapstructure:"ProvisionedConcurrencyConfig,omitempty"`

	// ReservedConcurrentExecutions corresponds to the JSON schema field
	// "ReservedConcurrentExecutions".
	ReservedConcurrentExecutions *int `json:"ReservedConcurrentExecutions,omitempty" yaml:"ReservedConcurrentExecutions,omitempty" mapstructure:"ReservedConcurrentExecutions,omitempty"`

	// Runtime corresponds to the JSON schema field "Runtime".
	Runtime *string `json:"Runtime,omitempty" yaml:"Runtime,omitempty" mapstructure:"Runtime,omitempty"`

	// RuntimeManagementConfig corresponds to the JSON schema field
	// "RuntimeManagementConfig".
	RuntimeManagementConfig *ResourcePropertiesRuntimeManagementConfig `json:"RuntimeManagementConfig,omitempty" yaml:"RuntimeManagementConfig,omitempty" mapstructure:"RuntimeManagementConfig,omitempty"`

	// Timeout corresponds to the JSON schema field "Timeout".
	Timeout *int `json:"Timeout,omitempty" yaml:"Timeout,omitempty" mapstructure:"Timeout,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type ResourcePropertiesProvisionedConcurrencyConfig struct {
	// ProvisionedConcurrentExecutions corresponds to the JSON schema field
	// "ProvisionedConcurrentExecutions".
	ProvisionedConcurrentExecutions *int `json:"ProvisionedConcurrentExecutions,omitempty" yaml:"ProvisionedConcurrentExecutions,omitempty" mapstructure:"ProvisionedConcurrentExecutions,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type ResourcePropertiesRuntimeManagementConfig struct {
	// UpdateRuntimeOn corresponds to the JSON schema field "UpdateRuntimeOn".
	UpdateRuntimeOn *string `json:"UpdateRuntimeOn,omitempty" yaml:"UpdateRuntimeOn,omitempty" mapstructure:"UpdateRuntimeOn,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type SamSchemaJson struct {
	// AWSTemplateFormatVersion corresponds to the JSON schema field
	// "AWSTemplateFormatVersion".
	AWSTemplateFormatVersion *string `json:"AWSTemplateFormatVersion,omitempty" yaml:"AWSTemplateFormatVersion,omitempty" mapstructure:"AWSTemplateFormatVersion,omitempty"`

	// Globals corresponds to the JSON schema field "Globals".
	Globals *SamSchemaJsonGlobals `json:"Globals,omitempty" yaml:"Globals,omitempty" mapstructure:"Globals,omitempty"`

	// Resources corresponds to the JSON schema field "Resources".
	Resources map[string]struct {
		// Properties corresponds to the JSON schema field "Properties".
		Properties *ResourceProperties `json:"Properties,omitempty" yaml:"Properties,omitempty" mapstructure:"Properties,omitempty"`

		// Type corresponds to the JSON schema field "Type".
		Type string `json:"Type" yaml:"Type" mapstructure:"Type"`

		AdditionalProperties interface{} `mapstructure:",remain"`
	} `json:"Resources" yaml:"Resources" mapstructure:"Resources"`

	// Transform corresponds to the JSON schema field "Transform".
	Transform interface{} `json:"Transform,omitempty" yaml:"Transform,omitempty" mapstructure:"Transform,omitempty"`
}

type SamSchemaJsonGlobals struct {
	// Function corresponds to the JSON schema field "Function".
	Function *SamSchemaJsonGlobalsFunction `json:"Function,omitempty" yaml:"Function,omitempty" mapstructure:"Function,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type SamSchemaJsonGlobalsFunction struct {
	// Architectures corresponds to the JSON schema field "Architectures".
	Architectures []string `json:"Architectures,omitempty" yaml:"Architectures,omitempty" mapstructure:"Architectures,omitempty"`

	// Environment corresponds to the JSON schema field "Environment".
	Environment *SamSchemaJsonGlobalsFunctionEnvironment `json:"Environment,omitempty" yaml:"Environment,omitempty" mapstructure:"Environment,omitempty"`

	// Handler corresponds to the JSON schema field "Handler".
	Handler *string `json:"Handler,omitempty" yaml:"Handler,omitempty" mapstructure:"Handler,omitempty"`

	// Layers corresponds to the JSON schema field "Layers".
	Layers []interface{} `json:"Layers,omitempty" yaml:"Layers,omitempty" mapstructure:"Layers,omitempty"`

	// MemorySize corresponds to the JSON schema field "MemorySize".
	MemorySize *int `json:"MemorySize,omitempty" yaml:"MemorySize,omitempty" mapstructure:"MemorySize,omitempty"`

	// Runtime corresponds to the JSON schema field "Runtime".
	Runtime *string `json:"Runtime,omitempty" yaml:"Runtime,omitempty" mapstructure:"Runtime,omitempty"`

	// RuntimeManagementConfig corresponds to the JSON schema field
	// "RuntimeManagementConfig".
	RuntimeManagementConfig *SamSchemaJsonGlobalsFunctionRuntimeManagementConfig `json:"RuntimeManagementConfig,omitempty" yaml:"RuntimeManagementConfig,omitempty" mapstructure:"RuntimeManagementConfig,omitempty"`

	// Timeout corresponds to the JSON schema field "Timeout".
	Timeout *int `json:"Timeout,omitempty" yaml:"Timeout,omitempty" mapstructure:"Timeout,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type SamSchemaJsonGlobalsFunctionEnvironment struct {
	// Variables corresponds to the JSON schema field "Variables".
	Variables map[string]interface{} `json:"Variables,omitempty" yaml:"Variables,omitempty" mapstructure:"Variables,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type SamSchemaJsonGlobalsFunctionRuntimeManagementConfig struct {
	// UpdateRuntimeOn corresponds to the JSON schema field "UpdateRuntimeOn".
	UpdateRuntimeOn *string `json:"UpdateRuntimeOn,omitempty" yaml:"UpdateRuntimeOn,omitempty" mapstructure:"UpdateRuntimeOn,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SamSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["Resources"]; raw != nil && !ok {
		return fmt.Errorf("field Resources in SamSchemaJson: required")
	}
	type Plain SamSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SamSchemaJson(plain)
	return nil
}
