// Code generated by tools/branding/generate.py; DO NOT EDIT.
// Where: cli/internal/constants/branding_gen.go
// What: Branding constants for CLI naming and resource prefixes.
// Why: Keep CLI-owned identifiers derived from the configured brand.
package constants

const (
	BrandingCLIName            = "esb"
	BrandingSlug               = "esb"
	BrandingEnvPrefix          = "ESB"
	BrandingImagePrefix        = "esb"
	BrandingLabelPrefix        = "com.esb"
	BrandingHomeDir            = ".esb"
	BrandingOutputDir          = ".esb"
	BrandingStagingDir         = ".staging"
	BrandingRootCAMountID      = "esb_root_ca"
	BrandingRootCACertFilename = "rootCA.crt"
)
